version: '3.8'

services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: inception-nginx
    env_file:
      - .env
    volumes:
      - inception-nginx-log:/var/log/nginx
      - inception-wordpress-html:/var/www/html/wordpress
    networks:
      - inception-network
    ports:
      - '443:443'
    depends_on:
      - mariadb
      - wordpress
  wordpress:
    restart: always
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: inception-wordpress
    env_file:
      - .env
    volumes:
      - inception-wordpress-html:/var/www/html/wordpress
    expose:
      - '9000'
    networks:
      - inception-network
    depends_on:
      - mariadb
  mariadb:
    restart: always
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: inception-mariadb
    env_file:
      - .env
    volumes:
      - inception-mariadb-data:/var/lib/mysql
    expose:
      - '3306'
    networks:
      - inception-network

volumes:
  inception-nginx-log:
    name: 'inception-nginx-log'
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/inception/nginx/log'
  inception-mariadb-data:
    name: 'inception-mariadb-data'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/inception/mariadb/data'
  inception-wordpress-html:
    name: 'inception-wordpress-html'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/inception/wordpress/html'

networks:
  inception-network:
    name: 'inception-network'
    driver: bridge
